import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const root = path.resolve(import.meta.dirname, '..');
const require = createRequire(path.join(root, 'client/aivorix-web/package.json'));
const ts = require('typescript');
const dataDir = path.join(root, 'client/aivorix-web/src/app/data');
const cache = new Map();
function readData(name) {
  const file = path.resolve(dataDir, name.endsWith('.ts') ? name : `${name}.ts`);
  if (cache.has(file)) return cache.get(file);
  const module = { exports: {} };
  const compiled = ts.transpileModule(fs.readFileSync(file, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
  }).outputText;
  new Function('require', 'module', 'exports', compiled)(readData, module, module.exports);
  cache.set(file, module.exports);
  return module.exports;
}

const { AI_TOOLS } = readData('tools.data');
const { NEWS } = readData('news.data');
const { COMPARISONS } = readData('comparisons.data');
const { HOME_BENCHMARKS, PRODUCT_SIGNALS } = readData('home-benchmarks.data');
const { AI_TOOL_DETAILS } = readData('tool-details.data');
const slugs = new Set(AI_TOOLS.map(tool => tool.slug));
for (const items of [AI_TOOLS, NEWS, COMPARISONS]) {
  assert.equal(new Set(items.map(item => item.slug)).size, items.length, 'Duplicate slug');
}
for (const comparison of COMPARISONS) {
  assert(slugs.has(comparison.left) && slugs.has(comparison.right), 'Invalid comparison tool');
  assert.notEqual(comparison.left, comparison.right);
}
for (const view of HOME_BENCHMARKS) {
  assert.deepEqual(new Set(view.entries.map(entry => entry.toolSlug)), slugs, `${view.slug}: incomplete coverage`);
  assert.equal(view.entries.length, slugs.size, 'Duplicate benchmark tool');
  let missing = false;
  for (const entry of view.entries) {
    if (entry.score === null) {
      missing = true;
      assert.equal(entry.displayScore, 'N/A');
    } else {
      assert(!missing, 'Ranked entries must precede unranked entries');
      assert(Number.isFinite(entry.score) && entry.score >= 0 && entry.score <= view.max);
    }
  }
  assert.equal(view.entries.find(entry => entry.toolSlug === 'gpt-6-astra').score, null,
    'Do not give Astra an unsupported score');
}
assert.deepEqual(new Set(PRODUCT_SIGNALS.map(signal => signal.toolSlug)), slugs);
assert(AI_TOOL_DETAILS['gpt-6-astra'].sources.length >= 3);
assert(NEWS.some(article => article.slug.includes('gpt-6-astra')));
assert(COMPARISONS.some(item => item.left === 'gpt-6-astra' || item.right === 'gpt-6-astra'));

const fixed = ['/', '/news', '/comparisons', '/compare', '/tools', '/about', '/methodology',
  '/editorial-policy', '/affiliate-disclosure', '/privacy', '/terms', '/contact', '/advertise'];
const paths = [...fixed, ...NEWS.map(x => `/news/${x.slug}`),
  ...COMPARISONS.map(x => `/comparisons/${x.slug}`), ...AI_TOOLS.map(x => `/tools/${x.slug}`)];
const quote = value => JSON.stringify(value);
const catalog = `// Generated by node scripts/check-content.mjs --sync-catalog\nnamespace Aivorix.Api.Data;\npublic static class SiteCatalog\n{\n    public static readonly string[] Paths = new[] { ${paths.map(quote).join(', ')} };\n    public static readonly (string Slug, string Date, string Title)[] News = new[] { ${NEWS.map(x => `(${quote(x.slug)}, ${quote(x.date)}, ${quote(x.title)})`).join(', ')} };\n}\n`;
const catalogPath = path.join(root, 'server/Aivorix.Api/Data/SiteCatalog.cs');
if (process.argv.includes('--sync-catalog')) fs.writeFileSync(catalogPath, catalog);
assert.equal(fs.readFileSync(catalogPath, 'utf8'), catalog, 'Backend catalog stale: run with --sync-catalog');

if (process.argv.includes('--prerender')) {
  const output = path.join(root, 'client/aivorix-web/dist/aivorix-web/browser');
  for (const route of paths) {
    const html = fs.readFileSync(path.join(output, route.slice(1), 'index.html'), 'utf8');
    assert(html.includes('<title>'), `Missing title: ${route}`);
    if (route.includes('gpt-6-astra') || ['/tools', '/news', '/comparisons', '/compare'].includes(route)) {
      assert(html.includes('GPT-6 Astra'), `Missing Astra: ${route}`);
    }
  }
  const home = fs.readFileSync(path.join(output, 'index.html'), 'utf8');
  assert(home.includes('Not ranked') && home.includes('N/A'), 'Missing honest unscored display');
}
console.log(`Content checks passed: ${AI_TOOLS.length} tools, ${NEWS.length} news, ${COMPARISONS.length} comparisons, ${paths.length} routes; every benchmark covers all tools.`);
